name: trovara
description: "Trovara"
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.8.1
  flutter: ">=3.41.2 <4.0.0"

dependencies:
  go_router: ^14.6.2
  connectivity_plus: ^6.1.5
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  # uni_links: ^0.5.1
  flutter_quill: ^11.4.2
  logger: ^2.6.1
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  file_selector: ^1.0.3
  path_provider: ^2.1.5
  file_picker: ^8.1.2
  flutter_svg: ^2.2.1
  flutter_gen: ^5.12.0
  fl_chart: ^0.68.0
  package_info_plus: ^9.0.0
  in_app_update: ^4.2.5
  url_launcher: ^6.3.1
  shelf: ^1.4.2
  webview_flutter: ^4.13.1
  pointycastle: ^4.0.0
  intl: ^0.20.2
  cupertino_native_better: ^1.3.4
  flutter_dynamic_icon_plus: ^1.4.0
  firebase_core: ^4.4.0
  path: ^1.9.1
  google_generative_ai: ^0.4.7
  uuid: ^4.5.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  objectbox_generator: ^4.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - shorebird.yaml
    - assets/translations/
    - assets/app_icon/
    - assets/icons/
