// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart' as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/chat_message.dart';
import 'models/chat_thread.dart';
import 'models/custom_tag.dart';
import 'models/folder.dart';
import 'models/note.dart';
import 'models/note_embedding.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7853034309261988721),
    name: 'Folder',
    lastPropertyId: const obx_int.IdUid(9, 4257404690156523047),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 606674975505403930), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 1742864662427377384), name: 'folderId', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 382270753060848855), name: 'name', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 2584906549294438755), name: 'description', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 1115292080584990461), name: 'color', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 1623072470652350997), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 910947762900366512), name: 'updatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 6784249753359974249), name: 'isDefault', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(9, 4257404690156523047), name: 'noteCount', type: 6, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6317312537730891446),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(21, 7892836430628886448),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 1772686458885544547), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 1276794422088069564), name: 'title', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 1947789243324082101), name: 'contentJson', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 6385277195119888875), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 8830280099423111436), name: 'updatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 8405630537741859686), name: 'isFavorite', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 1838127307021453792), name: 'isArchived', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 3956461929789338485), name: 'folderId', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(10, 2939021045952335524), name: 'moodTags', type: 30, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(11, 6279445950454810107), name: 'activityTags', type: 30, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(12, 8967983358329417601), name: 'timeTags', type: 30, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 331697692445163464),
        name: 'personalGrowthTags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(14, 4965465751400095188), name: 'customTagIds', type: 27, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(15, 706986872354415990), name: 'isDeleted', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(16, 4605642928560755925), name: 'deletedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(17, 1193297639825137982), name: 'driveFileId', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(18, 5331080527125817044), name: 'userId', type: 9, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6210228650839839360),
        name: 'syncId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 3825348798809574444),
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(20, 8261363560340761305), name: 'source', type: 9, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7892836430628886448),
        name: 'internalLinks',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8381765124324137753),
    name: 'CustomTag',
    lastPropertyId: const obx_int.IdUid(6, 7889005941927855266),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 678180135470757018), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 7435738613559352555), name: 'name', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 8321865262008596766), name: 'color', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 8416602076697062203), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 4686622472031572441), name: 'updatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 7889005941927855266), name: 'usageCount', type: 6, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6866622907400243735),
    name: 'NoteEmbedding',
    lastPropertyId: const obx_int.IdUid(9, 1201818448703780749),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 9082221737024787687), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 8621857554089024718), name: 'noteId', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 5155674640786982311), name: 'chunkIndex', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 1677348605704305491), name: 'chunkText', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 233286460839599742), name: 'embeddingData', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 1371899503158169796), name: 'modelVersion', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 8831101180634302375), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 2315417692093281007), name: 'noteUpdatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1201818448703780749),
        name: 'contentSignature',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7377808252709342167),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(9, 2695552612240637623),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 7994476633944570201), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 6540245522128006767), name: 'threadId', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 1545279623329235662), name: 'role', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 7830711602930305999), name: 'content', type: 9, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1196157311608539293),
        name: 'sourceNoteTitles',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 2745235701713919441), name: 'promptTokens', type: 6, flags: 0),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2556622503276782639),
        name: 'completionTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 5534313397560951003), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(9, 2695552612240637623), name: 'updatedAt', type: 10, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4384572733254933868),
    name: 'ChatThread',
    lastPropertyId: const obx_int.IdUid(8, 3116776367526658646),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 8074097225047784831), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 2668226591881984607), name: 'type', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 7424509450448170792), name: 'noteId', type: 6, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 997061733814873243), name: 'title', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 3443230629278171219), name: 'createdAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 5707112003871034383), name: 'updatedAt', type: 10, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 503645699165813515), name: 'isDeleted', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 3116776367526658646), name: 'deletedAt', type: 10, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 4384572733254933868),
    lastIndexId: const obx_int.IdUid(1, 3825348798809574444),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [7373197808855322801],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5283507406653816762,
      3314551958061198889,
      8724772223041090710,
      8872389228672845766,
      7348620165083816641,
      2376944311313385175,
      1413894492597862715,
      7561191491581535928,
      3139239441195315295,
      4069527587680502698,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Folder: obx_int.EntityDefinition<Folder>(
      model: _entities[0],
      toOneRelations: (Folder object) => [],
      toManyRelations: (Folder object) => {},
      getId: (Folder object) => object.id,
      setId: (Folder object, int id) {
        object.id = id;
      },
      objectToFB: (Folder object, fb.Builder fbb) {
        final folderIdOffset = fbb.writeString(object.folderId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null ? null : fbb.writeString(object.description!);
        final colorOffset = object.color == null ? null : fbb.writeString(object.color!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, folderIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, colorOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isDefault);
        fbb.addInt64(8, object.noteCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final folderIdParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final colorParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isDefaultParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
        final noteCountParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
        final object = Folder(
          id: idParam,
          folderId: folderIdParam,
          name: nameParam,
          description: descriptionParam,
          color: colorParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDefault: isDefaultParam,
          noteCount: noteCountParam,
        );

        return object;
      },
    ),
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[1],
      toOneRelations: (Note object) => [],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final contentJsonOffset = fbb.writeString(object.contentJson);
        final folderIdOffset = fbb.writeString(object.folderId);
        final moodTagsOffset = fbb.writeList(object.moodTags.map(fbb.writeString).toList(growable: false));
        final activityTagsOffset = fbb.writeList(object.activityTags.map(fbb.writeString).toList(growable: false));
        final timeTagsOffset = fbb.writeList(object.timeTags.map(fbb.writeString).toList(growable: false));
        final personalGrowthTagsOffset = fbb.writeList(
          object.personalGrowthTags.map(fbb.writeString).toList(growable: false),
        );
        final customTagIdsOffset = fbb.writeListInt64(object.customTagIds);
        final driveFileIdOffset = object.driveFileId == null ? null : fbb.writeString(object.driveFileId!);
        final userIdOffset = object.userId == null ? null : fbb.writeString(object.userId!);
        final syncIdOffset = fbb.writeString(object.syncId);
        final sourceOffset = fbb.writeString(object.source);
        final internalLinksOffset = fbb.writeList(object.internalLinks.map(fbb.writeString).toList(growable: false));
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, contentJsonOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isFavorite);
        fbb.addBool(6, object.isArchived);
        fbb.addOffset(7, folderIdOffset);
        fbb.addOffset(9, moodTagsOffset);
        fbb.addOffset(10, activityTagsOffset);
        fbb.addOffset(11, timeTagsOffset);
        fbb.addOffset(12, personalGrowthTagsOffset);
        fbb.addOffset(13, customTagIdsOffset);
        fbb.addBool(14, object.isDeleted);
        fbb.addInt64(15, object.deletedAt?.millisecondsSinceEpoch);
        fbb.addOffset(16, driveFileIdOffset);
        fbb.addOffset(17, userIdOffset);
        fbb.addOffset(18, syncIdOffset);
        fbb.addOffset(19, sourceOffset);
        fbb.addOffset(20, internalLinksOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedAtValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final syncIdParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 40, '');
        final titleParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final contentJsonParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
        final isArchivedParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
        final isDeletedParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false);
        final deletedAtParam = deletedAtValue == null ? null : DateTime.fromMillisecondsSinceEpoch(deletedAtValue);
        final driveFileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final userIdParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 38);
        final folderIdParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 18, '');
        final customTagIdsParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 30, []);
        final moodTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final activityTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 24, []);
        final timeTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final personalGrowthTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 28, []);
        final sourceParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 42, '');
        final internalLinksParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 44, []);
        final object = Note(
          id: idParam,
          syncId: syncIdParam,
          title: titleParam,
          contentJson: contentJsonParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isFavorite: isFavoriteParam,
          isArchived: isArchivedParam,
          isDeleted: isDeletedParam,
          deletedAt: deletedAtParam,
          driveFileId: driveFileIdParam,
          userId: userIdParam,
          folderId: folderIdParam,
          customTagIds: customTagIdsParam,
          moodTags: moodTagsParam,
          activityTags: activityTagsParam,
          timeTags: timeTagsParam,
          personalGrowthTags: personalGrowthTagsParam,
          source: sourceParam,
          internalLinks: internalLinksParam,
        );

        return object;
      },
    ),
    CustomTag: obx_int.EntityDefinition<CustomTag>(
      model: _entities[2],
      toOneRelations: (CustomTag object) => [],
      toManyRelations: (CustomTag object) => {},
      getId: (CustomTag object) => object.id,
      setId: (CustomTag object, int id) {
        object.id = id;
      },
      objectToFB: (CustomTag object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, colorOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.usageCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final nameParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final colorParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final usageCountParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
        final object = CustomTag(
          id: idParam,
          name: nameParam,
          color: colorParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          usageCount: usageCountParam,
        );

        return object;
      },
    ),
    NoteEmbedding: obx_int.EntityDefinition<NoteEmbedding>(
      model: _entities[3],
      toOneRelations: (NoteEmbedding object) => [],
      toManyRelations: (NoteEmbedding object) => {},
      getId: (NoteEmbedding object) => object.id,
      setId: (NoteEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (NoteEmbedding object, fb.Builder fbb) {
        final chunkTextOffset = fbb.writeString(object.chunkText);
        final embeddingDataOffset = fbb.writeString(object.embeddingData);
        final modelVersionOffset = fbb.writeString(object.modelVersion);
        final contentSignatureOffset = fbb.writeString(object.contentSignature);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.noteId);
        fbb.addInt64(2, object.chunkIndex);
        fbb.addOffset(3, chunkTextOffset);
        fbb.addOffset(4, embeddingDataOffset);
        fbb.addOffset(5, modelVersionOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.noteUpdatedAt.millisecondsSinceEpoch);
        fbb.addOffset(8, contentSignatureOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final noteIdParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
        final chunkIndexParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
        final chunkTextParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 10, '');
        final embeddingDataParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 12, '');
        final modelVersionParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 14, '');
        final contentSignatureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final noteUpdatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = NoteEmbedding(
          id: idParam,
          noteId: noteIdParam,
          chunkIndex: chunkIndexParam,
          chunkText: chunkTextParam,
          embeddingData: embeddingDataParam,
          modelVersion: modelVersionParam,
          contentSignature: contentSignatureParam,
          createdAt: createdAtParam,
          noteUpdatedAt: noteUpdatedAtParam,
        );

        return object;
      },
    ),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[4],
      toOneRelations: (ChatMessageEntity object) => [],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.id,
      setId: (ChatMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final roleOffset = fbb.writeString(object.role);
        final contentOffset = fbb.writeString(object.content);
        final sourceNoteTitlesOffset = fbb.writeList(
          object.sourceNoteTitles.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.threadId);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, sourceNoteTitlesOffset);
        fbb.addInt64(5, object.promptTokens);
        fbb.addInt64(6, object.completionTokens);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final threadIdParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
        final roleParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 10, '');
        final sourceNoteTitlesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final promptTokensParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
        final completionTokensParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = ChatMessageEntity(
          id: idParam,
          threadId: threadIdParam,
          role: roleParam,
          content: contentParam,
          sourceNoteTitles: sourceNoteTitlesParam,
          promptTokens: promptTokensParam,
          completionTokens: completionTokensParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    ChatThread: obx_int.EntityDefinition<ChatThread>(
      model: _entities[5],
      toOneRelations: (ChatThread object) => [],
      toManyRelations: (ChatThread object) => {},
      getId: (ChatThread object) => object.id,
      setId: (ChatThread object, int id) {
        object.id = id;
      },
      objectToFB: (ChatThread object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final titleOffset = object.title == null ? null : fbb.writeString(object.title!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addInt64(2, object.noteId);
        fbb.addOffset(3, titleOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(6, object.isDeleted);
        fbb.addInt64(7, object.deletedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedAtValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final typeParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final noteIdParam = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
        final titleParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
        final deletedAtParam = deletedAtValue == null ? null : DateTime.fromMillisecondsSinceEpoch(deletedAtValue);
        final object = ChatThread(
          id: idParam,
          type: typeParam,
          noteId: noteIdParam,
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
          deletedAt: deletedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Folder] entity fields to define ObjectBox queries.
class Folder_ {
  /// See [Folder.id].
  static final id = obx.QueryIntegerProperty<Folder>(_entities[0].properties[0]);

  /// See [Folder.folderId].
  static final folderId = obx.QueryStringProperty<Folder>(_entities[0].properties[1]);

  /// See [Folder.name].
  static final name = obx.QueryStringProperty<Folder>(_entities[0].properties[2]);

  /// See [Folder.description].
  static final description = obx.QueryStringProperty<Folder>(_entities[0].properties[3]);

  /// See [Folder.color].
  static final color = obx.QueryStringProperty<Folder>(_entities[0].properties[4]);

  /// See [Folder.createdAt].
  static final createdAt = obx.QueryDateProperty<Folder>(_entities[0].properties[5]);

  /// See [Folder.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Folder>(_entities[0].properties[6]);

  /// See [Folder.isDefault].
  static final isDefault = obx.QueryBooleanProperty<Folder>(_entities[0].properties[7]);

  /// See [Folder.noteCount].
  static final noteCount = obx.QueryIntegerProperty<Folder>(_entities[0].properties[8]);
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[1].properties[0]);

  /// See [Note.title].
  static final title = obx.QueryStringProperty<Note>(_entities[1].properties[1]);

  /// See [Note.contentJson].
  static final contentJson = obx.QueryStringProperty<Note>(_entities[1].properties[2]);

  /// See [Note.createdAt].
  static final createdAt = obx.QueryDateProperty<Note>(_entities[1].properties[3]);

  /// See [Note.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Note>(_entities[1].properties[4]);

  /// See [Note.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Note>(_entities[1].properties[5]);

  /// See [Note.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Note>(_entities[1].properties[6]);

  /// See [Note.folderId].
  static final folderId = obx.QueryStringProperty<Note>(_entities[1].properties[7]);

  /// See [Note.moodTags].
  static final moodTags = obx.QueryStringVectorProperty<Note>(_entities[1].properties[8]);

  /// See [Note.activityTags].
  static final activityTags = obx.QueryStringVectorProperty<Note>(_entities[1].properties[9]);

  /// See [Note.timeTags].
  static final timeTags = obx.QueryStringVectorProperty<Note>(_entities[1].properties[10]);

  /// See [Note.personalGrowthTags].
  static final personalGrowthTags = obx.QueryStringVectorProperty<Note>(_entities[1].properties[11]);

  /// See [Note.customTagIds].
  static final customTagIds = obx.QueryIntegerVectorProperty<Note>(_entities[1].properties[12]);

  /// See [Note.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Note>(_entities[1].properties[13]);

  /// See [Note.deletedAt].
  static final deletedAt = obx.QueryDateProperty<Note>(_entities[1].properties[14]);

  /// See [Note.driveFileId].
  static final driveFileId = obx.QueryStringProperty<Note>(_entities[1].properties[15]);

  /// See [Note.userId].
  static final userId = obx.QueryStringProperty<Note>(_entities[1].properties[16]);

  /// See [Note.syncId].
  static final syncId = obx.QueryStringProperty<Note>(_entities[1].properties[17]);

  /// See [Note.source].
  static final source = obx.QueryStringProperty<Note>(_entities[1].properties[18]);

  /// See [Note.internalLinks].
  static final internalLinks = obx.QueryStringVectorProperty<Note>(_entities[1].properties[19]);
}

/// [CustomTag] entity fields to define ObjectBox queries.
class CustomTag_ {
  /// See [CustomTag.id].
  static final id = obx.QueryIntegerProperty<CustomTag>(_entities[2].properties[0]);

  /// See [CustomTag.name].
  static final name = obx.QueryStringProperty<CustomTag>(_entities[2].properties[1]);

  /// See [CustomTag.color].
  static final color = obx.QueryStringProperty<CustomTag>(_entities[2].properties[2]);

  /// See [CustomTag.createdAt].
  static final createdAt = obx.QueryDateProperty<CustomTag>(_entities[2].properties[3]);

  /// See [CustomTag.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CustomTag>(_entities[2].properties[4]);

  /// See [CustomTag.usageCount].
  static final usageCount = obx.QueryIntegerProperty<CustomTag>(_entities[2].properties[5]);
}

/// [NoteEmbedding] entity fields to define ObjectBox queries.
class NoteEmbedding_ {
  /// See [NoteEmbedding.id].
  static final id = obx.QueryIntegerProperty<NoteEmbedding>(_entities[3].properties[0]);

  /// See [NoteEmbedding.noteId].
  static final noteId = obx.QueryIntegerProperty<NoteEmbedding>(_entities[3].properties[1]);

  /// See [NoteEmbedding.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<NoteEmbedding>(_entities[3].properties[2]);

  /// See [NoteEmbedding.chunkText].
  static final chunkText = obx.QueryStringProperty<NoteEmbedding>(_entities[3].properties[3]);

  /// See [NoteEmbedding.embeddingData].
  static final embeddingData = obx.QueryStringProperty<NoteEmbedding>(_entities[3].properties[4]);

  /// See [NoteEmbedding.modelVersion].
  static final modelVersion = obx.QueryStringProperty<NoteEmbedding>(_entities[3].properties[5]);

  /// See [NoteEmbedding.createdAt].
  static final createdAt = obx.QueryDateProperty<NoteEmbedding>(_entities[3].properties[6]);

  /// See [NoteEmbedding.noteUpdatedAt].
  static final noteUpdatedAt = obx.QueryDateProperty<NoteEmbedding>(_entities[3].properties[7]);

  /// See [NoteEmbedding.contentSignature].
  static final contentSignature = obx.QueryStringProperty<NoteEmbedding>(_entities[3].properties[8]);
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<ChatMessageEntity>(_entities[4].properties[0]);

  /// See [ChatMessageEntity.threadId].
  static final threadId = obx.QueryIntegerProperty<ChatMessageEntity>(_entities[4].properties[1]);

  /// See [ChatMessageEntity.role].
  static final role = obx.QueryStringProperty<ChatMessageEntity>(_entities[4].properties[2]);

  /// See [ChatMessageEntity.content].
  static final content = obx.QueryStringProperty<ChatMessageEntity>(_entities[4].properties[3]);

  /// See [ChatMessageEntity.sourceNoteTitles].
  static final sourceNoteTitles = obx.QueryStringVectorProperty<ChatMessageEntity>(_entities[4].properties[4]);

  /// See [ChatMessageEntity.promptTokens].
  static final promptTokens = obx.QueryIntegerProperty<ChatMessageEntity>(_entities[4].properties[5]);

  /// See [ChatMessageEntity.completionTokens].
  static final completionTokens = obx.QueryIntegerProperty<ChatMessageEntity>(_entities[4].properties[6]);

  /// See [ChatMessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ChatMessageEntity>(_entities[4].properties[7]);

  /// See [ChatMessageEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ChatMessageEntity>(_entities[4].properties[8]);
}

/// [ChatThread] entity fields to define ObjectBox queries.
class ChatThread_ {
  /// See [ChatThread.id].
  static final id = obx.QueryIntegerProperty<ChatThread>(_entities[5].properties[0]);

  /// See [ChatThread.type].
  static final type = obx.QueryStringProperty<ChatThread>(_entities[5].properties[1]);

  /// See [ChatThread.noteId].
  static final noteId = obx.QueryIntegerProperty<ChatThread>(_entities[5].properties[2]);

  /// See [ChatThread.title].
  static final title = obx.QueryStringProperty<ChatThread>(_entities[5].properties[3]);

  /// See [ChatThread.createdAt].
  static final createdAt = obx.QueryDateProperty<ChatThread>(_entities[5].properties[4]);

  /// See [ChatThread.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ChatThread>(_entities[5].properties[5]);

  /// See [ChatThread.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<ChatThread>(_entities[5].properties[6]);

  /// See [ChatThread.deletedAt].
  static final deletedAt = obx.QueryDateProperty<ChatThread>(_entities[5].properties[7]);
}
